# Generated by Django 4.0.2 on 2022-02-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicalInstruments',
        ),
    ]
