# Generated by Django 4.0.2 on 2022-03-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_games_delete_musics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'traditionalGames',
            },
        ),
    ]
