# Generated by Django 4.0.2 on 2022-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_traditionalgames'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TraditionalGames',
        ),
    ]
