# Generated by Django 4.0.2 on 2022-03-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_details_delete_traditionalgames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='picture',
        ),
    ]
