# Generated by Django 4.0.2 on 2022-03-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_clothes_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.RemoveField(
            model_name='customs',
            name='num',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
    ]
