# Generated by Django 4.0.3 on 2022-04-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_delete_details_remove_customs_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
