# Generated by Django 4.0.3 on 2022-04-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_new_acc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_acc',
            new_name='User',
        ),
    ]
