# Generated by Django 4.0.3 on 2022-04-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_rename_new_acc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('date_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('price_low', models.FloatField()),
                ('price_high', models.FloatField()),
            ],
        ),
    ]
