# Generated by Django 4.0.3 on 2022-04-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_stocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stocks',
            new_name='stock',
        ),
    ]
